name: nfcr
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  nfc_manager: 3.3.0
  sqflite: ^2.3.0
  path: ^1.8.3
  permission_handler: ^11.0.1
  file_picker: ^8.0.0+1
  share_plus: ^10.0.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
